name: TP2 Devops
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
        /*secrets.DOCKER_USERNAME and secrets.DOCKER_PASSWORD parameters are set to access your 
        Docker Hub account credentials, which are stored as GitHub secrets.*/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: my-docker-image:latest

