name: TP2 Devops
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on : ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
        continue-on-error: true



      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220105_Harmantepe_Melis:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220105_Harmantepe_Melis:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220105_Harmantepe_Melis:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: 20220105_Harmantepe_Melis
          location: 'west us'

      
    #  - name: Build and push Docker image
    #    uses: docker/build-push-action@v2.1.0
    #    with:
     #     context: ./TP3
     #     file: ./TP3/Dockerfile
     #     push: true
     #     tags: mharmantepe/tp2:1.0.0
      
