name: TP2 Devops
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on : ubuntu-latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./TP2
          push: true
          tags: my-docker-image:latest

