name: TP2 Devops
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on : ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Check Lint errors with Hadolint
        uses: hadolint/hadolint-action@v1.1.0
        with:
          dockerfile: ./TP2/Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./TP2
          file: ./TP2/Dockerfile
          push: true
          tags: mharmantepe/tp2:1.0.0
      
